name: ci

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - 
        name: Build downloader image
        id: docker_build_downloader
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          load: false
          cache-from: |
            type=gha,scope=downloader
          cache-to: |
            type=gha,scope=downloader
          target: downloader
      - 
        name: Build builder image
        id: docker_build_builder
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          load: false
          cache-from: |
            type=gha,scope=builder
          cache-to: |
            type=gha,scope=builder
          target: builder
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            akkuman/av-toolset:${{ env.RELEASE_VERSION }}
            akkuman/av-toolset:latest
          cache-from: |
            type=gha,scope=finally
            type=gha,scope=downloader
            type=gha,scope=builder
          cache-to: type=gha,scope=finally
          target: finally
